In [16]:
import numpy as np
import os

array1 = np.zeros((5,10), dtype = np.int16)
print(array1)

array2 = np.ones((5,10))
print(array2)

array3 = np.arange(1,10,2)
print(array3)

from numpy import pi
array4 = np.linspace(5,10,10)
print(array4)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[1 3 5 7 9]
[ 5.          5.55555556  6.11111111  6.66666667  7.22222222  7.77777778
  8.33333333  8.88888889  9.44444444 10.        ]
